# services:
#   mysqldb:
#     image: mysql:5.7
#     container_name: mysqldb
#     restart: unless-stopped
#     environment:
#       MYSQL_DATABASE: chatgpt
#       MYSQL_ROOT_PASSWORD: 753951
#       MYSQL_USER: db_user
#       MYSQL_PASSWORD: db_user_pass
#     healthcheck:
#       test: ["CMD-SHELL", 'mysqladmin ping']
#       interval: 10s
#       timeout: 2s
#       retries: 10
#     ports:
#       - 3306:3306
#     volumes:
#       - dbdata:/var/lib/mysql
#     networks:
#      - spring-network
#   chatgptapi-service:
#     depends_on:
#       mysqldb:
#         condition: service_healthy
#     build:
#       context: ./
#     restart: always
#     ports:
#       - 8080:8080
#     volumes:
#       - .m2:/root/.
#     networks:
#      - spring-network
# volumes:
#   dbdata:
# networks:
#   spring-network:
#     driver: bridge

version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/chatgpt?enabledTLSProtocols=TLSv1.2
    depends_on:
      mysqldb:
        condition: service_completed_successfully
    
    volumes:
      - .m2:/root/.m2
      
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net  
    environment:
      MYSQL_DATABASE: chatgpt
      MYSQL_USER: root
      MYSQL_PASSWORD: 753951
      MYSQL_ROOT_PASSWORD: 753951
networks:
  springapimysql-net: