name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-job:
    runs-on: self-hosted
    steps:
      - working-directory: ./"Week 2/Day 4/Exercice 1/chatgpt-api"/
        run: ls
        run: ./mvn clean package

  test-job1:
    runs-on: self-hosted
    steps:
      - working-directory: ./"Week 2/Day 4/Exercice 1/chatgpt-api"/
        run: ls
        run: docker-compose up -d