name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-job:
    runs-on: self-hosted
    steps:
      - run: echo "Hello, $GITLAB_USER_LOGIN!"

  test-job1:
    runs-on: self-hosted
    steps:
      - run: echo "This job tests something"

  test-job2:
    runs-on: self-hosted
    steps:
      - run: echo "This job tests something, but takes more time than test-job1."
      - run: echo "After the echo commands complete, it runs the sleep command for 20 seconds"
      - run: echo "which simulates a test that runs 20 seconds longer than test-job1"
      - run: sleep 20
  deploy-prod:
    runs-on: self-hosted
    steps:
      - run: echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v