name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        working-directory: "Week 2/Day 4/Exercice 1/chatgpt-api"
        run: | 
          ls
          chmod +x ./mvnw
          ./mvnw --batch-mode --update-snapshots clean install

  # test-job1:
  #   runs-on: self-hosted
  #   steps:
  #     - working-directory: "Week 2/Day 4/Exercice 1/chatgpt-api"
  #       run: ls
  #     - working-directory: "Week 2/Day 4/Exercice 1/chatgpt-api"
  #       run: docker-compose up -d