name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-job:
    runs-on: self-hosted
    steps:
      - run: echo "Hello, $GITLAB_USER_LOGIN!"

  test-job1:
    runs-on: self-hosted
    steps:
      - run: ls