name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-job:
    runs-on: self-hosted
    steps:
      - uses: maven:latest
      - working-directory: "Week 2/Day 4/Exercice 1/chatgpt-api"
        run: |
          ls
          chmod +x ./mvnw
          ./mvnw clean package

  # test-job1:
  #   runs-on: self-hosted
  #   steps:
  #     - working-directory: "Week 2/Day 4/Exercice 1/chatgpt-api"
  #       run: ls
  #     - working-directory: "Week 2/Day 4/Exercice 1/chatgpt-api"
  #       run: docker-compose up -d